#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

app_controllers:
  resource: "../src/Controller/"
  type: annotation

program_show:
  path: "/programs/{slug}"
  controller: 'App\Controller\ProgramController::show'
  methods: ["GET"]
  requirements:
    slug: "[a-zA-Z0-9-_]+"

episode_edit:
  path: "/episode/{slug}/edit"
  controller: 'App\Controller\EpisodeController::edit'
  methods: ["GET", "POST"]
  requirements:
    slug: "[a-zA-Z0-9-]+"

comment_show:
  path: /comment/{id}
  controller: 'App\Controller\CommentController::show'
  methods: ["GET"]

comment_edit:
  path: "/comment/{id}/edit"
  controller: 'App\Controller\CommentController::edit'
  methods: ["GET", "POST"]
  requirements:
    id: '\d+'
